In [128]:
import pandas as pd
tweets = pd.read_csv('tweet_data/Tweet.csv')
tweets = tweets[tweets['like_num'] > 2] #more than 2 likes
tweets['post_date'] = pd.to_datetime(tweets['post_date'],unit='s') #change epoch time

In [129]:
tweets_simplify = tweets.copy()
tweets_simplify

,tweet_id,writer,post_date,body,comment_num,retweet_num,like_num
23,550453087731982336,DCaptura,2015-01-01 00:46:57,"""http://iphone.appleinsider.com/articles/14/12...",0,3,3
25,550453624258965505,WSJ,2015-01-01 00:49:05,Jeff Bezos lost $7.4 billion in Amazon's worst...,21,139,57
52,550465988442214400,valuewalk,2015-01-01 01:38:13,$MU $AAPL $SUNE Propel Greenlight To 9% Return...,0,0,4
84,550479777006497792,themotleyfool,2015-01-01 02:33:00,"#FoolFaves2014 Lo, how the mighty have fallen?...",0,7,5
92,550489146624856064,CNBC,2015-01-01 03:10:14,"Earlier this month, a mysterious glitch caused...",4,18,17
...,...,...,...,...,...,...,...
3717933,1212151032014237697,vistapglobal,2019-12-31 23:18:21,“It’s A Wrap” Vista Partners Daily Market Reca...,0,3,3
3717934,1212152718640472064,decampkev,2019-12-31 23:25:03,Most bulls understand that quite well. In fact...,1,0,3
3717939,1212154167185289216,Commuternyc,2019-12-31 23:30:48,Nah This will be a trip! Especially without a ...,0,0,3
3717959,1212159765914079234,TEEELAZER,2019-12-31 23:53:03,That $SPY $SPX puuump in the last hour was the...,1,0,6
3717961,1212160015332728833,Commuternyc,2019-12-31 23:54:03,Patiently Waiting for the no twitter sitter tw...,0,0,5

In [130]:
tweets_simplify.drop('writer', inplace=True, axis=1)
tweets_simplify.drop('comment_num', inplace=True, axis=1)
tweets_simplify.drop('retweet_num', inplace=True, axis=1)
#remove tweet_id, writer, comment_num, retweet_num

In [131]:
tweets_simplify

,tweet_id,post_date,body,like_num
23,550453087731982336,2015-01-01 00:46:57,"""http://iphone.appleinsider.com/articles/14/12...",3
25,550453624258965505,2015-01-01 00:49:05,Jeff Bezos lost $7.4 billion in Amazon's worst...,57
52,550465988442214400,2015-01-01 01:38:13,$MU $AAPL $SUNE Propel Greenlight To 9% Return...,4
84,550479777006497792,2015-01-01 02:33:00,"#FoolFaves2014 Lo, how the mighty have fallen?...",5
92,550489146624856064,2015-01-01 03:10:14,"Earlier this month, a mysterious glitch caused...",17
...,...,...,...,...
3717933,1212151032014237697,2019-12-31 23:18:21,“It’s A Wrap” Vista Partners Daily Market Reca...,3
3717934,1212152718640472064,2019-12-31 23:25:03,Most bulls understand that quite well. In fact...,3
3717939,1212154167185289216,2019-12-31 23:30:48,Nah This will be a trip! Especially without a ...,3
3717959,1212159765914079234,2019-12-31 23:53:03,That $SPY $SPX puuump in the last hour was the...,6
3717961,1212160015332728833,2019-12-31 23:54:03,Patiently Waiting for the no twitter sitter tw...,5

In [132]:
tweets_simplify['post_date'] = tweets_simplify['post_date'] + pd.DateOffset(days=7) #offset date by 1 week
tweets_simplify = tweets_simplify[tweets_simplify['post_date'] < '2015-01-09'] #filter post_date
tweets_simplify

,tweet_id,post_date,body,like_num
23,550453087731982336,2015-01-08 00:46:57,"""http://iphone.appleinsider.com/articles/14/12...",3
25,550453624258965505,2015-01-08 00:49:05,Jeff Bezos lost $7.4 billion in Amazon's worst...,57
52,550465988442214400,2015-01-08 01:38:13,$MU $AAPL $SUNE Propel Greenlight To 9% Return...,4
84,550479777006497792,2015-01-08 02:33:00,"#FoolFaves2014 Lo, how the mighty have fallen?...",5
92,550489146624856064,2015-01-08 03:10:14,"Earlier this month, a mysterious glitch caused...",17
105,550499176422051840,2015-01-08 03:50:06,Jeff Bezos lost $7.4 billion in Amazon's worst...,57
166,550539994159669249,2015-01-08 06:32:17,Wow! $AAPL #mobile MT @stevesi 'Computing powe...,4
254,550650235404701697,2015-01-08 13:50:21,Analyst Report on Top Stock Market Options for...,3
269,550661290184945664,2015-01-08 14:34:17,"See how tech companies like Apple, Twitter and...",3
274,550663510498095104,2015-01-08 14:43:06,"2015 Tech Forecast: Clouds, Wearables, Cyberse...",3
310,550677995753857024,2015-01-08 15:40:39,"See how tech companies like Apple, Twitter and...",4
315,550679033395306497,2015-01-08 15:44:47,"New Post - ""Apple Stock Pullback: Price Target...",7
343,550690489008394241,2015-01-08 16:30:18,2015 technology forecasts: Wearable technology...,11
353,550696363407986688,2015-01-08 16:53:39,"New Post - ""Apple Stock Pullback: Price Target...",3
375,550705849690116096,2015-01-08 17:31:20,IBD:2015 technology forecasts: Wearable techno...,3
382,550708630291361793,2015-01-08 17:42:23,Kirill Klip.: China Extends Electric-Car Incen...,3
394,550713309117562880,2015-01-08 18:00:59,Memo to @elonmusk: Tesla's accounting is as cr...,6
399,550716105573269506,2015-01-08 18:12:06,$AAPL Risk into Earnings Rising Early (pic)dat...,3
400,550716527503478784,2015-01-08 18:13:46,Memo to @elonmusk: Blocking me on twitter won'...,14
409,550721191238176770,2015-01-08 18:32:18,Memo to @elonmusk: Thank's for the trophy! Get...,4
428,550727326300778497,2015-01-08 18:56:41,.@Microsoft to eliminate original #Kinect for ...,3
439,550732338670227457,2015-01-08 19:16:36,"Today's apps gone free: Decide Now, OftenType,...",3
447,550738868652507137,2015-01-08 19:42:33,@SamAntar$TSLA does a lot of things to manipul...,3
468,550749669060407297,2015-01-08 20:25:28,"Long BlackBerry, Short Apple Again In 2015 htt...",5
472,550752071243141120,2015-01-08 20:35:00,"We're shocked, shocked! that Samsung might try...",9
495,550758844922486784,2015-01-08 21:01:55,$aapl could be a problem sitting on support th...,3
521,550774071210696704,2015-01-08 22:02:26,4 Value Stocks For 2015 http://seekingalpha.co...,5
525,550777620422729728,2015-01-08 22:16:32,"New hed, same story: The Apple press goes off ...",8
531,550779709840445441,2015-01-08 22:24:50,"See how tech companies like Apple, Twitter and...",109
536,550781053137616896,2015-01-08 22:30:10,This is Wall Street's top pick in 2015. Hint: ...,22
563,550793247669231616,2015-01-08 23:18:38,video going out . happy new year . talking $aa...,3
564,550793298357391360,2015-01-08 23:18:50,"#bluechips like $TSLA, $AAPL, $DIS, $TWTR & NV...",3
581,550802957370159104,2015-01-08 23:57:13,"An $AAPL store line in Sapporo Japan for the ""...",4

In [133]:
company_tweet = pd.read_csv('tweet_data/Company_Tweet.csv')
company_tweet

                    tweet_id ticker_symbol
0         550803612197457920          AAPL
1         550803610825928706          AAPL
2         550803225113157632          AAPL
3         550802957370159104          AAPL
4         550802855129382912          AAPL
...                      ...           ...
4336440  1212158772015034369          TSLA
4336441  1212159099632267268          TSLA
4336442  1212159184931717120          TSLA
4336443  1212159838882533376          TSLA
4336444  1212160015332728833          TSLA

[4336445 rows x 2 columns]

In [134]:
tweets_simplify = pd.merge(tweets_simplify, company_tweet, left_on='tweet_id', right_on='tweet_id')
tweets_simplify['post_date'] = tweets_simplify['post_date'].dt.normalize() #get rid of time

In [136]:
tweets_simplify

,tweet_id,post_date,body,like_num,ticker_symbol
0,550453087731982336,2015-01-08,"""http://iphone.appleinsider.com/articles/14/12...",3,AAPL
1,550453087731982336,2015-01-08,"""http://iphone.appleinsider.com/articles/14/12...",3,GOOG
2,550453624258965505,2015-01-08,Jeff Bezos lost $7.4 billion in Amazon's worst...,57,AMZN
3,550465988442214400,2015-01-08,$MU $AAPL $SUNE Propel Greenlight To 9% Return...,4,AAPL
4,550479777006497792,2015-01-08,"#FoolFaves2014 Lo, how the mighty have fallen?...",5,AAPL
5,550489146624856064,2015-01-08,"Earlier this month, a mysterious glitch caused...",17,AAPL
6,550499176422051840,2015-01-08,Jeff Bezos lost $7.4 billion in Amazon's worst...,57,AMZN
7,550539994159669249,2015-01-08,Wow! $AAPL #mobile MT @stevesi 'Computing powe...,4,AAPL
8,550650235404701697,2015-01-08,Analyst Report on Top Stock Market Options for...,3,AAPL
9,550650235404701697,2015-01-08,Analyst Report on Top Stock Market Options for...,3,AMZN
10,550661290184945664,2015-01-08,"See how tech companies like Apple, Twitter and...",3,AAPL
11,550663510498095104,2015-01-08,"2015 Tech Forecast: Clouds, Wearables, Cyberse...",3,AAPL
12,550663510498095104,2015-01-08,"2015 Tech Forecast: Clouds, Wearables, Cyberse...",3,GOOGL
13,550663510498095104,2015-01-08,"2015 Tech Forecast: Clouds, Wearables, Cyberse...",3,AMZN
14,550663510498095104,2015-01-08,"2015 Tech Forecast: Clouds, Wearables, Cyberse...",3,MSFT
15,550677995753857024,2015-01-08,"See how tech companies like Apple, Twitter and...",4,AAPL
16,550679033395306497,2015-01-08,"New Post - ""Apple Stock Pullback: Price Target...",7,AAPL
17,550690489008394241,2015-01-08,2015 technology forecasts: Wearable technology...,11,AAPL
18,550690489008394241,2015-01-08,2015 technology forecasts: Wearable technology...,11,AMZN
19,550690489008394241,2015-01-08,2015 technology forecasts: Wearable technology...,11,MSFT
20,550696363407986688,2015-01-08,"New Post - ""Apple Stock Pullback: Price Target...",3,AAPL
21,550705849690116096,2015-01-08,IBD:2015 technology forecasts: Wearable techno...,3,AAPL
22,550705849690116096,2015-01-08,IBD:2015 technology forecasts: Wearable techno...,3,AMZN
23,550705849690116096,2015-01-08,IBD:2015 technology forecasts: Wearable techno...,3,MSFT
24,550708630291361793,2015-01-08,Kirill Klip.: China Extends Electric-Car Incen...,3,TSLA
25,550713309117562880,2015-01-08,Memo to @elonmusk: Tesla's accounting is as cr...,6,TSLA
26,550716105573269506,2015-01-08,$AAPL Risk into Earnings Rising Early (pic)dat...,3,AAPL
27,550716527503478784,2015-01-08,Memo to @elonmusk: Blocking me on twitter won'...,14,TSLA
28,550721191238176770,2015-01-08,Memo to @elonmusk: Thank's for the trophy! Get...,4,TSLA
29,550727326300778497,2015-01-08,.@Microsoft to eliminate original #Kinect for ...,3,MSFT
30,550732338670227457,2015-01-08,"Today's apps gone free: Decide Now, OftenType,...",3,AAPL
31,550738868652507137,2015-01-08,@SamAntar$TSLA does a lot of things to manipul...,3,TSLA
32,550749669060407297,2015-01-08,"Long BlackBerry, Short Apple Again In 2015 htt...",5,AAPL
33,550752071243141120,2015-01-08,"We're shocked, shocked! that Samsung might try...",9,AAPL
34,550758844922486784,2015-01-08,$aapl could be a problem sitting on support th...,3,AAPL
35,550774071210696704,2015-01-08,4 Value Stocks For 2015 http://seekingalpha.co...,5,AAPL
36,550777620422729728,2015-01-08,"New hed, same story: The Apple press goes off ...",8,AAPL
37,550779709840445441,2015-01-08,"See how tech companies like Apple, Twitter and...",109,AAPL
38,550781053137616896,2015-01-08,This is Wall Street's top pick in 2015. Hint: ...,22,AAPL
39,550793247669231616,2015-01-08,video going out . happy new year . talking $aa...,3,AAPL
40,550793298357391360,2015-01-08,"#bluechips like $TSLA, $AAPL, $DIS, $TWTR & NV...",3,AAPL
41,550793298357391360,2015-01-08,"#bluechips like $TSLA, $AAPL, $DIS, $TWTR & NV...",3,TSLA
42,550802957370159104,2015-01-08,"An $AAPL store line in Sapporo Japan for the ""...",4,AAPL

In [137]:
body = [str(i) for i in tweets_simplify['body'].values]
ticker = [str(i) for i in tweets_simplify['ticker_symbol'].values]

In [150]:
price = pd.read_csv('stock_price/CompanyValues.csv')
price['change'] = (price['close_value'] - price['open_value']).round(2) #calculate weekly change
price = price[price['day_date'] < '2015-01-09']
price = price[price['day_date'] > '2015-01-07']
price

,ticker_symbol,day_date,close_value,volume,open_value,high_value,low_value,change
1356,AAPL,2015-01-08,111.890,59168760,109.23,112.1500,108.70,2.66
4441,AMZN,2015-01-08,300.460,3087475,300.32,303.1400,296.11,0.14
7526,GOOGL,2015-01-08,506.910,3661816,501.51,507.5000,495.02,5.40
10611,GOOG,2015-01-08,502.680,3341935,497.99,503.4800,491.00,4.69
12734,MSFT,2015-01-08,47.590,29634030,46.75,47.7499,46.72,0.84
15819,TSLA,2015-01-08,210.615,3434901,212.81,213.7999,210.01,-2.19

In [141]:
price['day_date'] = price['day_date'].astype('datetime64[ns]')
tweets_simplify = pd.merge(tweets_simplify, price, left_on=['post_date', 'ticker_symbol'], right_on=['day_date', 'ticker_symbol'], how = 'left')

In [142]:
tweets_simplify.drop('close_value', inplace=True, axis=1)
tweets_simplify.drop('volume', inplace=True, axis=1)
tweets_simplify.drop('open_value', inplace=True, axis=1)
tweets_simplify.drop('high_value', inplace=True, axis=1)
tweets_simplify.drop('low_value', inplace=True, axis=1)

In [153]:
tweets_simplify['post_date'] = tweets_simplify['post_date']+ pd.DateOffset(days=-7) #offset date by 1 week
apple_tweets = tweets_simplify.loc[tweets_simplify['ticker_symbol'] == 'AAPL']
apple_tweets

,tweet_id,post_date,body,like_num,ticker_symbol,day_date,change
0,550453087731982336,2014-12-18,"""http://iphone.appleinsider.com/articles/14/12...",3,AAPL,2015-01-08,2.66
3,550465988442214400,2014-12-18,$MU $AAPL $SUNE Propel Greenlight To 9% Return...,4,AAPL,2015-01-08,2.66
4,550479777006497792,2014-12-18,"#FoolFaves2014 Lo, how the mighty have fallen?...",5,AAPL,2015-01-08,2.66
5,550489146624856064,2014-12-18,"Earlier this month, a mysterious glitch caused...",17,AAPL,2015-01-08,2.66
7,550539994159669249,2014-12-18,Wow! $AAPL #mobile MT @stevesi 'Computing powe...,4,AAPL,2015-01-08,2.66
8,550650235404701697,2014-12-18,Analyst Report on Top Stock Market Options for...,3,AAPL,2015-01-08,2.66
10,550661290184945664,2014-12-18,"See how tech companies like Apple, Twitter and...",3,AAPL,2015-01-08,2.66
11,550663510498095104,2014-12-18,"2015 Tech Forecast: Clouds, Wearables, Cyberse...",3,AAPL,2015-01-08,2.66
15,550677995753857024,2014-12-18,"See how tech companies like Apple, Twitter and...",4,AAPL,2015-01-08,2.66
16,550679033395306497,2014-12-18,"New Post - ""Apple Stock Pullback: Price Target...",7,AAPL,2015-01-08,2.66
17,550690489008394241,2014-12-18,2015 technology forecasts: Wearable technology...,11,AAPL,2015-01-08,2.66
20,550696363407986688,2014-12-18,"New Post - ""Apple Stock Pullback: Price Target...",3,AAPL,2015-01-08,2.66
21,550705849690116096,2014-12-18,IBD:2015 technology forecasts: Wearable techno...,3,AAPL,2015-01-08,2.66
26,550716105573269506,2014-12-18,$AAPL Risk into Earnings Rising Early (pic)dat...,3,AAPL,2015-01-08,2.66
30,550732338670227457,2014-12-18,"Today's apps gone free: Decide Now, OftenType,...",3,AAPL,2015-01-08,2.66
32,550749669060407297,2014-12-18,"Long BlackBerry, Short Apple Again In 2015 htt...",5,AAPL,2015-01-08,2.66
33,550752071243141120,2014-12-18,"We're shocked, shocked! that Samsung might try...",9,AAPL,2015-01-08,2.66
34,550758844922486784,2014-12-18,$aapl could be a problem sitting on support th...,3,AAPL,2015-01-08,2.66
35,550774071210696704,2014-12-18,4 Value Stocks For 2015 http://seekingalpha.co...,5,AAPL,2015-01-08,2.66
36,550777620422729728,2014-12-18,"New hed, same story: The Apple press goes off ...",8,AAPL,2015-01-08,2.66
37,550779709840445441,2014-12-18,"See how tech companies like Apple, Twitter and...",109,AAPL,2015-01-08,2.66
38,550781053137616896,2014-12-18,This is Wall Street's top pick in 2015. Hint: ...,22,AAPL,2015-01-08,2.66
39,550793247669231616,2014-12-18,video going out . happy new year . talking $aa...,3,AAPL,2015-01-08,2.66
40,550793298357391360,2014-12-18,"#bluechips like $TSLA, $AAPL, $DIS, $TWTR & NV...",3,AAPL,2015-01-08,2.66
42,550802957370159104,2014-12-18,"An $AAPL store line in Sapporo Japan for the ""...",4,AAPL,2015-01-08,2.66

In [144]:
stock_price = [str(i) for i in tweets_simplify['change'].values]

In [145]:
%store body
%store ticker
%store tweets_simplify
%store stock_price

Stored 'body' (list)
Stored 'ticker' (list)
Stored 'tweets_simplify' (DataFrame)
Stored 'stock_price' (list)