In [26]:
import pandas as pd
import datetime

df_tweets_original = pd.read_csv(r'./tweet_dataset/Tweet.csv')
df_company_tweet = pd.read_csv(r'./tweet_dataset/Company_Tweet.csv')

df_tweets = pd.merge(df_tweets_original, df_company_tweet, on='tweet_id', how='left')

df_tweets['post_date'] =  pd.to_datetime(df_tweets['post_date'], unit='s').dt.floor('d')
df_tweets = df_tweets.loc[df_tweets['like_num'] > 2]
df_tweets_aapl = df_tweets.loc[df_tweets['ticker_symbol'] == 'AAPL']
df_tweets_aapl

,tweet_id,writer,post_date,body,comment_num,retweet_num,like_num,ticker_symbol
35,550453087731982336,DCaptura,2015-01-01,"""http://iphone.appleinsider.com/articles/14/12...",0,3,3,AAPL
70,550465988442214400,valuewalk,2015-01-01,$MU $AAPL $SUNE Propel Greenlight To 9% Return...,0,0,4,AAPL
111,550479777006497792,themotleyfool,2015-01-01,"#FoolFaves2014 Lo, how the mighty have fallen?...",0,7,5,AAPL
119,550489146624856064,CNBC,2015-01-01,"Earlier this month, a mysterious glitch caused...",4,18,17,AAPL
198,550539994159669249,IanGertler,2015-01-01,Wow! $AAPL #mobile MT @stevesi 'Computing powe...,0,4,4,AAPL
...,...,...,...,...,...,...,...,...
4336399,1212146665303498759,leadlagreport,2019-12-31,#Netflix continues to grow its global subscrib...,0,2,5,AAPL
4336407,1212149840261480448,momotrader,2019-12-31,i think many retail folks early next week will...,0,0,8,AAPL
4336408,1212150279656890374,luke_sosnowski,2019-12-31,Great day and years end over at #TRICKTRADES m...,1,2,7,AAPL
4336411,1212151032014237697,vistapglobal,2019-12-31,“It’s A Wrap” Vista Partners Daily Market Reca...,0,3,3,AAPL
4336439,1212159765914079234,TEEELAZER,2019-12-31,That $SPY $SPX puuump in the last hour was the...,1,0,6,AAPL